language: java
dist: trusty
sudo: false

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer


script: ./gradlew clean build --no-daemon

after_success:
  - ./gradlew jacocoTestReport coveralls --no-daemon
#  - ./gradlew test cobertura coveralls --no-daemon