language: java
dist: trusty
sudo: false

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer


script: ./gradlew clean unitTest build -x test  --no-daemon

after_success:
  - ./gradlew unitTest cobertura coveralls -x test  --no-daemon